---
- name: Install Jenkins
  hosts: jenkins
  become: true
  roles:
    - { role: jenkins, tags: jenkins }

- name: Install Postgresql
  hosts: postgresql
  become: true
  roles:
    - { role: postgresql, tags: postgresql }
